name: firebase_test_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  go_router: ^14.2.3
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/construction_login_image.jpeg
  - assets/CAT_Icon.jpg
  - assets/Text.svg
  - assets/Analysis_donut.svg
  - assets/half_star.svg
  - assets/home.svg
  - assets/home1.png
  - assets/mic.svg
  - assets/support_agent.svg
  - assets/mail.svg
  - assets/call.svg
  - assets/sound.svg
  - assets/pause.svg
  - assets/headphones.svg
  - assets/note.svg
  - assets/add_photo.svg
  - assets/image.svg
  - assets/voice.svg
  - assets/wheel.svg
  - assets/settings.svg
  - assets/brake.svg
  - assets/machine.svg
  - assets/battery.svg
  - assets/map.svg

  
