name: firebase_test_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.3
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^5.2.1
  easy_stepper: ^0.8.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/construction_login_image.jpeg
  - assets/CAT_Icon.jpg
  - assets/tire_icon.svg
  - assets/tire_icon.png
  - assets/battery_charging_icon.png
  - assets/exterior_truck_icon.png
  - assets/voice_over_record_icon.png
  - assets/brake_icon.png

